# Stock and Sales

## LDV Stock by vehicle size
```{r}
tot <- "Stock|Transport|Pass|Road|LDV"
items <- c("Stock|Transport|Pass|Road|LDV|Four Wheelers|Medium|Compact Car",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV",
           "Stock|Transport|Pass|Road|LDV|Midsize Car",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Mini Car",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car",
           "Stock|Transport|Pass|Road|")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Sales by vehicle size
```{r}
tot <- "Sales|Transport|Pass|Road|LDV"
items <- c("Sales|Transport|Pass|Road|LDV|Four Wheelers|Medium|Compact Car",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV",
           "Sales|Transport|Pass|Road|LDV|Midsize Car",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Mini Car",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car",
           "Sales|Transport|Pass|Road|")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Stock by technology
```{r}
tot <- "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car"
items <- c("Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|BEV",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|FCEV",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|Hybrid electric",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|Liquids",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Sales by technology
```{r}
tot <- "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car"
items <- c("Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|BEV",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|FCEV",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|Hybrid electric",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|Liquids",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Small|Subcompact Car|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Stock by technology
```{r}
tot <- "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV"
items <- c("Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|BEV",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|FCEV",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|Hybrid electric",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|Liquids",
           "Stock|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## LDV Sales by technology
```{r}
tot <- "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV"
items <- c("Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|BEV",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|FCEV",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|Hybrid electric",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|Liquids",
           "Sales|Transport|Pass|Road|LDV|Four Wheelers|Large|Large Car and SUV|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Busses
```{r}
tot <- "Stock|Transport|Pass|Road|Bus"
items <- c("Stock|Transport|Pass|Road|Bus|BEV",
           "Stock|Transport|Pass|Road|Bus|FCEV",
           "Stock|Transport|Pass|Road|Bus|Liquids",
           "Stock|Transport|Pass|Road|Bus|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Truck stock by size
```{r}
tot <- "Stock|Transport|Freight|Road|Truck"
items <- c("Stock|Transport|Freight|Road|Truck (0-3_5t)",
           "Stock|Transport|Freight|Road|Truck (7_5t)",
           "Stock|Transport|Freight|Road|Truck (18t)",
           "Stock|Transport|Freight|Road|Truck (26t)",
           "Stock|Transport|Freight|Road|Truck (40t)")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Truck sales by size
```{r}
tot <- "Sales|Transport|Freight|Road|Truck"
items <- c("Sales|Transport|Freight|Road|truck (0-3_5t)",
           "Sales|Transport|Freight|Road|truck (7_5t)",
           "Sales|Transport|Freight|Road|Truck (18t)",
           "Sales|Transport|Freight|Road|Truck (26t)",
           "Sales|Transport|Freight|Road|Truck (40t)")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Small Truck stock by technology
```{r}
tot <- "Stock|Transport|Freight|Road|Truck (0-3_5t)"
items <- c("Stock|Transport|Freight|Road|Truck (0-3_5t)|BEV",
           "Stock|Transport|Freight|Road|Truck (0-3_5t)|FCEV",
           "Stock|Transport|Freight|Road|Truck (0-3_5t)|Liquids",
           "Stock|Transport|Freight|Road|Truck (0-3_5t)|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Small Truck sales by technology
```{r}
tot <- "Sales|Transport|Freight|Road|Truck (0-3_5t)"
items <- c("Sales|Transport|Freight|Road|Truck (0-3_5t)|BEV",
           "Sales|Transport|Freight|Road|Truck (0-3_5t)|FCEV",
           "Sales|Transport|Freight|Road|Truck (0-3_5t)|Liquids",
           "Sales|Transport|Freight|Road|Truck (0-3_5t)|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Large Truck stock by technology
```{r}
tot <- "Stock|Transport|Freight|Road|Truck (40t)"
items <- c("Stock|Transport|Freight|Road|Truck (40t)|BEV",
           "Stock|Transport|Freight|Road|Truck (40t)|FCEV",
           "Stock|Transport|Freight|Road|Truck (40t)|Liquids",
           "Stock|Transport|Freight|Road|Truck (40t)|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```

## Large Truck sales by technology
```{r}
tot <- "Sales|Transport|Freight|Road|Truck (40t)"
items <- c("Sales|Transport|Freight|Road|Truck (40t)|BEV",
           "Sales|Transport|Freight|Road|Truck (40t)|FCEV",
           "Sales|Transport|Freight|Road|Truck (40t)|Liquids",
           "Sales|Transport|Freight|Road|Truck (40t)|NG")
showAreaAndBarPlots(data, items, tot, orderVars = "user")
showAreaAndBarPlots(data, items, tot, fill = TRUE, orderVars = "user")
```
