# Energy Intensities
## Passenger per vkm
```{r}
items <- c(
          "Energy Intensity|Transport|Pass",
          "Energy Intensity|Transport|Bunkers|Pass|International Aviation",
          "Energy Intensity|Transport|Pass|Rail",
          "Energy Intensity|Transport|Pass|Domestic Aviation",
          "Energy Intensity|Transport|Pass|Road",
          "Energy Intensity|Transport|Pass|Road|LDV",
          "Energy Intensity|Transport|Pass|Road|LDV|Four Wheelers",
          "Energy Intensity|Transport|Pass|Road|LDV|Two Wheelers",
          "Energy Intensity|Transport|Pass|Road|Bus"
  )
walk(items, showLinePlots, data = data, scales = "fixed")
```

## Freight per vkm
```{r}
items <- c(
            "Energy Intensity|Transport|Freight",
            "Energy Intensity|Transport|Bunkers|Freight|International Shipping",
            "Energy Intensity|Transport|Freight|Domestic Shipping",
            "Energy Intensity|Transport|Freight|Rail",
            "Energy Intensity|Transport|Freight|Road"
  )
walk(items, showLinePlots, data = data, scales = "fixed")
```